networks:
  laravel:

volumes:
  mysqldata:
  redisdata:

services:
  instance:
    build:
      context: ./.docker/apache
      dockerfile: apache.dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database
      - redis
      - composer
      - npm
      - artisan
    networks:
      - laravel
    container_name: instance

  database:
    image: mariadb:${MARIADB_VERSION}
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel
    container_name: database

  redis:
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - laravel
    container_name: redis

  composer:
    image: composer:latest
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel
    container_name: composer

  npm:
    image: node:latest
    volumes:
      - ./src:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel
    container_name: npm

  artisan:
    build:
      context: ./.docker/php
      dockerfile: php.dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
    container_name: artisan
